#!/usr/bin/perl -w
#
# Amahi Home Server
# Copyright (C) 2007-2009 Amahi Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

# web based installer front end

use strict;
use Getopt::Std;
use POSIX qw(strftime);

our($opt_f, $opt_h);
getopts('fh');

my $LOG = "/tmp/amahi-ruby-install.log";
my $ICF = "/var/hda/install-code.txt";
my $platform = "EE";

# FIXME support ubuntu too
sub get_platform {
	open (my $file, "< /etc/issue") or return "EE";
	my $p = <$file>;
	chomp $p;
	if ($p =~ /Fedora/) {
		return "fedora"
	}
	if ($p =~ /Ubuntu|Debian/) {
		return "debian"
	}

	return "EE";
}

# sleep and exit, so that it's not restarted too quickly
sub sleep_and_exit {
	my $code = shift;

	sleep(2);
	exit($code);
}

sub daemonize {
	my $pid = fork;
	if ($pid < 0) {
		print STDERR "ERROR: can not fork/detach ($!)\n";
		&sleep_and_exit(-1);
	} elsif ($pid) {
		# parent simply exit
		exit 0;
	}
	# chil continues execution
	$SIG{'CHLD'}   = 'DEFAULT';
	open(STDOUT, ">$LOG");
	open(STDERR, ">$LOG");
	open(STDIN,  "</dev/null");
}


sub do_system_multiple () {
	my $args = shift;

	# attempt the install at most this times
	my $times = 10;
	my $res = 0;
	my $i = 0;

	foreach (1..$times) {
		last unless ($res = system ($args . " &> $LOG"));
	}

	return $res;
}

sub do_basic_checks {
	$ENV{PATH} .= ":/sbin:/usr/sbin:/bin";
	my $ruid = $<;
	my $euid = $>;

	$platform = &get_platform();

	if ($opt_h) {
		printf "usage: amahi-installer [-f|-h]\n";
		printf "\t -h  - help\n";
		printf "\t -f  - force\n";
		&sleep_and_exit(1);
	}
	if ($euid != 0) {
		printf "ERROR: this program must be run as \"root\". type \"su\" (to Switch User to root),\n";
		printf "       then input your root password, then run this program again.\n\n";
		printf "       \$ su\n";
		printf "       Password:         (enter your root password)\n";
		&sleep_and_exit(1);
	}
	if (-e "/etc/sysconfig/amahi-hda") {
		if ($opt_f) {
			printf "WARNING: this system is already intialized for Amahi use\n";
		} else {
			# exit silently
			printf "the system already has Amahi installed.\n";
			&sleep_and_exit(0);
		}
	}
}

sub package_installed () {
	my $pkg = shift;

	return (system("rpm -q $pkg &> /dev/null") == 0);
}

sub gem_installed () {
        my $gem = shift;
        my $ret = system("gem list ^$gem\$ | grep -q $gem &> /dev/null");
        return ($ret ? 0 : 1);
}

sub install_rpm_packages() {
	&do_system_multiple("yum -y install ruby") unless &package_installed("ruby");
	&do_system_multiple("yum -y install ruby-mysql") unless &package_installed("ruby-mysql");
	&do_system_multiple("yum -y install rubygem-rack") unless &package_installed("rubygem-rack");
	&do_system_multiple("yum -y install rubygem-sinatra") unless &package_installed("rubygem-sinatra");
}

sub install_packages() {
	if ($platform eq "fedora") {
		&install_rpm_packages();
	}
}

&do_basic_checks();

if (-e "$ICF") {
	# delayed express install
	printf "starting the express installer.\n";
	open(my $aicf, "< $ICF") || die ("cannot open the install code $ICF: $!");
	my $aic = <$aicf>;
	chomp($aic);
	my $logfile = strftime("/root/hda-install-express-%y%m%d-%H%M%S.log", localtime);
	# run the installer!
	my $result = system("hda-install $aic &> $logfile");
	if ($result == 0) {
		printf "Amahi express installer finished successfully. Rebooting.\n";
		system("reboot");
	} else {
		printf "WARNING: express installer failed to start!\n";
	}
}

printf "starting the web-based installer at:\n";
printf "\thttp://localhost:2000\n\n";
printf "For help:\n";
printf "\t- visit http://talk.amahi.org for live community help\n";
# if the above fails, still run the web installer
&install_packages();
&daemonize;
exec("/usr/share/hda-ctl/web-installer/install-server &> $LOG");
# sleep, in case it fails
warn "FATAL: web installer failed to start!\n";
&sleep_and_exit(-1);
