#!/usr/bin/env ruby
#
# Amahi Home Server
# Copyright (C) 2007-2009 Amahi Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

DATABASE_NAME = "hda_production"
DATABASE_USER = "amahihda"
DATABASE_PASSWORD = "AmahiHDARulez"
DATABASE_MAIN_USER = "root"
DATABASE_MAIN_PASSWORD = "hda"
GREYHOLE_DATABASE = "greyhole"

OLDOUT = $stdout.dup

def message(m)
	OLDOUT.print m
	OLDOUT.print "\n"
	OLDOUT.flush
end

def re_initialize_greyhole
	message "Initializing Storage Pooling ..."
	db = open "| mysql --user #{DATABASE_MAIN_USER} -p#{DATABASE_MAIN_PASSWORD} 2>&1", "r+"
	dbname = user = user_password = GREYHOLE_DATABASE
	host = "localhost"
	if db
		db.puts "drop database if exists `#{dbname}`;"
		db.puts "create database `#{dbname}`;"
		db.puts "create user '#{user}'@'#{host}' IDENTIFIED BY '#{user_password}';"
		db.puts "grant all privileges on `#{dbname}`.* to '#{user}'@'#{host}';"
		db.puts "use greyhole;"
		open("/usr/share/greyhole/schema-mysql.sql") do |f|
			until (f.eof) do
				db.puts f.readline
			end
		end
		db.puts "quit"
		db.flush
		db.close
	else
		raise "cannot create greyole db!!"
	end

	message "IMPORTANT: you must go to your disk pooling settings page "
	message "    http://hda/setup?sub=disk_pooling&tab=share"
	message "and change AT LEAST ONE setting. This will refresh the Greyhole configuration."
	message "You can revert the setting if you want. Then go to Setup > Setting > Servers"
	message "and verify that Greyhole is running!"
end

def update_rails
	message "Updating rails ..."
	system "gem install --no-ri --no-rdoc -v=2.3.4 rails"
	Dir.chdir("/var/hda/platform/html") do
		message "Updating Amahi DB."
		system "rake db:migrate RAILS_ENV=production"
		message "Restarting Dashboard."
		system "touch tmp/restart.txt"
	end
end

def main
	message "Starting ..."
	update_rails
	re_initialize_greyhole
	message "*************************************"
	message "* Done upgrading to Amahi 6! Enjoy! *"
	message "*************************************"
end

main
