#!/usr/bin/perl
#
# Amahi Home Server
# Copyright (C) 2007-2009 Amahi Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."
#
# re-register all apps

sub do_register_installed_apps {

	my $file = "";
	my @files = glob("/var/hda/platform/apps/*/app-register");
	foreach $file (@files) {
		if ($file =~ /\/var\/hda\/platform\/apps\/([^\/]+)\//) {
			printf "Registering app '$1'.\n";
		}
		system("bash $file");
	}
}

&do_register_installed_apps();
