#!/usr/bin/ruby

def do_php_timezone

	unless File.symlink?("/etc/localtime")
		puts "Global PHP timezone setup failed!"
		return
	end

	# supported php timezones http://us1.php.net/manual/en/timezones.php
	require 'augeas'
	Augeas::open do |aug|
		zone = File.realpath("/etc/localtime")
		zone.sub! /.*zoneinfo\//, ''
		aug.set("/files/etc/php.ini/Date/date.timezone", zone)
		# the save is broken in f14 see https://fedorahosted.org/augeas/ticket/149
		if aug.save
			puts "PHP timezone successfully changed to: #{zone}"
		else
			puts "Failed to save PHP Timezone changes to /etc/php.ini!"
		end
	end
end

do_php_timezone
